name: Goodreads Currently Reading

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.goodreads.com/review/list_rss/200266565-h-o-nguy-n?shelf=currently-reading"
          comment_tag_name: "GOODREADS-LIST"
          template: '<table><tr><td align="center" width="180"><a href="$url"><img src="$cover" width="128" alt="$title" /><br/><strong>$title</strong><br/><sub>by $author</sub></a></td></tr></table>'
          max_post_count: 5
          commit_message: "docs: update currently reading books"
          custom_tags: "cover/media:content/@url,author/dc:creator"
